image: docker:latest
stages:
  - deploy

deploy_job:
  stage: deploy
  image: npm:latest
  tags:
    - be-run
  before_script:
 
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $SSH_USER@$SSH_HOST "cd /home/fusion/Workspace/bookstore/backend; git pull origin main"
    - ssh $SSH_USER@$SSH_HOST "cd /home/fusion/Workspace/bookstore/backend; npm install"
    - ssh $SSH_USER@$SSH_HOST "cd /home/fusion/Workspace/bookstore/backend; npm run build"
    - ssh $SSH_USER@$SSH_HOST "cd /home/fusion/Workspace/bookstore/backend; pm2 reload backend"
  only:
    - main
