image: docker:latest
stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - be-run
  before_script:
 
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $SSH_USER@$SSH_HOST "cd /home/ubuntu/projects/bookstore-back/backend; ls -al"
    - ssh $SSH_USER@$SSH_HOST "cd /home/ubuntu/projects/bookstore-back/backend; npm i"
    - ssh $SSH_USER@$SSH_HOST "cd /home/ubuntu/projects/bookstore-back/backend; npm run build"
    - ssh $SSH_USER@$SSH_HOST "cd /home/ubuntu/projects/bookstore-back/backend; pm2 start npm --name "backend" -- start"
  only:
    - main
