image: docker:latest
stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - be-run

  before_script:
                - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
                - mkdir -p ~/.ssh
                - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
                - chmod 700 ~/.ssh/id_rsa
                - eval "$(ssh-agent -s)"
                - ssh-add ~/.ssh/id_rsa
                - ssh-keyscan -t rsa $SSH_HOST > ~/.ssh/known_hosts
                - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
                - chmod 644 ~/.ssh/known_hosts
  #before_script:
 
#    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
 #   - eval $(ssh-agent -s)
 #   - ssh-add <(echo "$SSH_PRIVATE_KEY")
 #   - mkdir -p ~/.ssh
 #   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $SSH_USER@$SSH_HOST "cd /home/fusion/Workspace/bookstore/backend; ls -la"
   # - ssh $SSH_USER@$SSH_HOST "cd /home/fusion/Workspace/bookstore/backend; npm i"
   # - ssh $SSH_USER@$SSH_HOST "cd /home/fusion/Workspace/bookstore/backend; npm run build"
   # - ssh $SSH_USER@$SSH_HOST "cd /home/fusion/Workspace/bookstore/backend; pm2 start npm --name "back" -- start"
  only:
    - main
